/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import java.io.File;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Scanner;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;

public class App {
	public void getGreeting() {
		String path = "Student Information";
		File file = new File(path);
		boolean bool = file.exists();
		if(!bool)
			file.mkdir();
		while(!info.Login.login());
		Scanner s = new Scanner(System.in);

		int choice;
		do
		{

			new info.Menu();
			choice = s.nextInt();
			switch(choice)
			{
				case 1:
					new student.Registration();
					break;
				case 2:
					new student.Search();
					break;
				case 3:
					new info.Information();
					break;
				case 4:
					new info.Rules();
					break;
				case 5:
					System.out.println("\n\t\t\tThank You");
					break;
				default:
					System.out.println("Enter Correct Choice");
					break;
			}
		}while(choice!=5);
	}

	public static void main(String[] args) {
		new App().getGreeting();
	}
}
